name: Publish plots

on:
  push:
    paths:
      - 'plots/*'
    branches:    
      - 'main'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: read yaml settings gh-pages
      id: read-yaml-gh-pages
      uses:  KJ002/read-yaml@main
      with: 
        file: './instructor/settings.yml'
        key-path: '["gh-pages"]'   
    - name: Deploy ðŸš€
      if: |
        steps.read-yaml-gh-pages.outputs.data == 'true' ||
        steps.read-yaml-gh-pages.outputs.data == 'True'
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: plots # The folder the action should deploy.
        target-folder: plots
        commit-message: publish plots
        clean: false
        git-config-name: choochoo-bot
        git-config-email:  <>


